settings:
  command-system:
    disabled-commands:
      - ""
  conversions:
    auto-convert: true # Do you want to auto-convert other tag plugins to implement the tags from them?
  chat-system:
    enabled: true # This will use the chat system, and format your chat for you!
    format: "%prefix%%player%&7: &f%message%" # This is how messages will appear in chat.
  storage:
    drive: "MONGO" # Available Options: MYSQL, MONGO
    mongo:
      address: "127.0.0.1"
      port: 27017
      database_name: "Calcium"
      auth:
        enabled: false
        user: "admin"
        password: ""
    mysql:
      host: ""
      port: 3306
      database: "Calcium"
      user: "root"
      password: ""
  selected_tag:
    - "&aYou have successfully selected this tag."
  added_favourite:
    - "&aYou have added the &6%tag% &aas a favourite!"
  removed_favourite:
    - "&cYou have removed the &6%tag% &cas a favourite."
  menu:
    title: "&8Tag Menu"
    raw: 3
    fill:
      enabled: true
      data: 15