settings:
  storage:
    drive: "MONGO" # Available Options: MYSQL, MONGO
    mongo:
      address: "127.0.0.1"
      port: 27017
      database_name: "Calcium"
      auth:
        enabled: false
        user: "admin"
        password: ""
    mysql:
      host: ""
      port: 3306
      database: "Calcium"
      user: "root"
      password: ""
  selected_tag:
    - "&aYou have successfully selected this tag."
  menu:
    title: "&8Tag Menu"
    raw: 3
    fill:
      enabled: true
      data: 15

categorys:
  common:
    item: 54
    data: 0
    amount: 1
    slot: 12
    displayname: "&eCommon Chat Prefixes"
    lore:
      - "&7This category contains all of"
      - "&7the &aCommon Chat Prefixes&7!"
      - ""
      - "&6Left-Click &7to open this category."
    menu:
      title: "&9Common tags"
  country:
    item: 54
    data: 0
    amount: 1
    slot: 16
    displayname: "&cCountry Chat Prefixes"
    lore:
      - "&7This category contains all of"
      - "&7the &cCountry Chat Prefixes&7!"
      - ""
      - "&6Left-Click &7to open this category."
    menu:
      title: "&9Country tags"