settings:
  storage:
    drive: "YML"

    mysql:
      host: ""
      port: 3306
      database: "Neon"
      user: "root"
      password: ""

  selected_tag:
    - "&aYou have successfully selected this tag"

  menu:
    main:
      title: "&9&lNeon tags"
      raw: 3
      fill:
        enabled: true
        data: 15

categorys:
  common:
    item: 54
    data: 0
    amount: 1
    slot: 12
    displayname: "&eCommon category"
    lore:
      - ""
      - "&7Click to open common category"
      - ""
    menu:
      title: "&9Common tags"
  country:
    item: 54
    data: 0
    amount: 1
    slot: 16
    displayname: "&eCountry category"
    lore:
      - ""
      - "&7Click to open country category"
      - ""
    menu:
      title: "&9Country tags"